### ISSUE TITLE
Feature Request: Change port and enable SSL

### ISSUE THREAD

**Issue by BadCoder12** [nesaku/BiblioReads-Docker#3]
I was hoping we can do a environment variable to change the port and also enable SSL?

**Comment by nesaku** [comment]
Hey [BadCoder12](https://github.com/BadCoder12), 

You can already edit the exposed port using the `docker-compose.yml` file or the Docker CLI and it is recommended to use a reverse proxy to enable SSL.

For example, to change the exposed host port to 8080 use:
```
    ports: 
      - "8080:3000"
```
for `docker-compose.yml` or
```
  -p 8080:3000 
```
for the Docker CLI.
