### ISSUE TITLE
Deprecated warning on modules

### ISSUE THREAD

**Issue by BadCoder12** [nesaku/BiblioReads-Docker#4]
(node:18) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by nesaku** [comment]
Hello BadCoder12,

Thank you for creating this issue. This is no longer an issue in BiblioReads https://github.com/nesaku/BiblioReads/commit/4721bef162a96c9e68fe84c5e3770e2a66341dec (v3.0.0).
